#!/system/bin/sh
#
# Script to start "am" on the device, which has a very rudimentary
# shell.
#
base=/system
export CLASSPATH=$base/framework/sca.jar
exec app_process $base/bin com.nick.commands.sca.Sca "$@"

